### ISSUE TITLE
Possibility to split CSS / Angular dependencies ?

### ISSUE THREAD

**Issue by sponnet** [Antwerp-Operating-System/sass_css_js_tink#1]
If I want to use the styles in another frontend framework, or want to use it without a frontend framework altogether - it might be nice to have the framework split into 2 parts : a tink and tink-angular package for example. Just a thought.

**Comment by TriangleJuice** [comment]
Hi Stefaan, since we thought your request was a very good idea, we just did that. Only we took it a step further: all our components and themes are now separate repositories. You can find them here: [https://github.com/tinkkit](https://github.com/tinkkit)

Just give us some more time to get the documentation fixed :-)

**Comment by kingflurkel** [comment]
This starts to look more and more like Polymer web components :)

**Comment by clopin** [comment]
@kingflurkel your way of saying 'good'? ;)

**Comment by TriangleJuice** [comment]
@kingflurkel Yup! Misschien dat ge u geroepen voelt om een Polymer versie te bouwen van één van onze directives? :-)

@clopin +1

**Comment by kingflurkel** [comment]
Will do!

**Comment by kingflurkel** [comment]
@clopin +1 :)
